### ISSUE TITLE
Need Some Info about how flow works

### ISSUE THREAD

**Issue by nitinpund** [ethercreative/yii2-app-api#1]
Hi Matt,

Its really a nice rest api, thanks for it. As I am new to Yii2, it is hard for me to understand some basic things. Can you provide some info about how authorisation works?

Thanks

**Comment by archlemon** [comment]
I'll assume you've managed to set up the app and db, and quickly show you how to register/login.

You can register using:

```
POST /register/
{
    "email":"me@example.com",
    "display_name":"me",
    "password":"example"
}
```

Which will return an `access_token` and a `refresh_token`, along with their expiry time.

`access_token` is short lived bearer token, and needs to be sent in the `Authorization` header. E.g. `Authorization: Bearer abc123`

To log into an existing account you can use:

```
POST /register/
{
    "email":"me@example.com",
    "password":"example"
}
```

Which will return the same data as registering.

You can use the `refresh_token`, which is long lived, to obtain a new `access_token` if it has expired or about to.

```
POST /auth/token/
{
    "refresh_token":"ynVD4zZgs0u55fSCUkBDWfe1zP1JGmIAUip0wRjoeep634XQI57t_sFU6q1Rr1sU"
}
```
